# Generated by Django 2.2 on 2020-11-10 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('citizenID', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)])),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('ownerFlag', models.BooleanField(default=True)),
                ('ownerRating', models.FloatField()),
                ('ctFlag', models.BooleanField(default=True)),
                ('caretakerRating', models.FloatField()),
            ],
        ),
    ]
